# Generated by Django 3.2.4 on 2021-12-19 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название отдела')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Фамилия сотрудника')),
                ('sallary', models.IntegerField(verbose_name='Зарплата')),
                ('departmentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rk.department')),
            ],
        ),
    ]
